// Generated by CoffeeScript 1.6.2
(function() {
  var __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(root, factory) {
    if (typeof exports === "object") {
      return module.exports = factory();
    } else if (typeof define === "function" && define.amd) {
      return define(factory);
    } else {
      return root.emvy = factory();
    }
  })(this, function() {
    var Attributed, Base, Computing, Element, Evented, Hiding, Model, View, ViewCollection, ViewModel;

    Evented = function(tag) {
      var callbacks, downstream, upstream;

      callbacks = {};
      upstream = [];
      downstream = [];
      return function() {
        var that;

        that = this;
        this.attach = function(something, up, oneway) {
          if (!up) {
            downstream.push(something);
            if (!oneway) {
              return something.attach(this, true);
            }
          } else {
            return upstream.push(something);
          }
        };
        this.detach = function(something, up, oneway) {
          var index;

          if (!up) {
            index = downstream.indexOf(something);
            downstream.splice(index, 1);
            if (!oneway) {
              return something.detach(this, true);
            }
          } else {
            index = upstream.indexOf(something);
            return upstream.splice(index, 1);
          }
        };
        this.on = function(action, callback) {
          var actions, _i, _len;

          actions = action.split(" ");
          for (_i = 0, _len = actions.length; _i < _len; _i++) {
            action = actions[_i];
            callbacks[action] || (callbacks[action] = []);
            callbacks[action].push(callback);
          }
          return this;
        };
        this.once = function(action, callback) {
          var cb;

          return this.on(action, cb = function() {
            this.off(action, cb);
            return callback.apply(this, arguments);
          });
        };
        this.trigger = function() {
          var action, actions, args, callback, item, parts, resolved, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2;

          action = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
          actions = action.split(" ");
          for (_i = 0, _len = actions.length; _i < _len; _i++) {
            action = actions[_i];
            resolved = false;
            if (callbacks[action]) {
              _ref = callbacks[action];
              for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
                callback = _ref[_j];
                if (callback.apply(that, args) === true) {
                  resolved = true;
                }
              }
            }
            if (!resolved) {
              if (tag) {
                parts = action.split(":");
                if (parts.length > 1) {
                  parts[1] = tag + "." + parts[1];
                } else {
                  parts[1] = tag;
                }
                action = parts.join(":");
              }
              for (_k = 0, _len2 = downstream.length; _k < _len2; _k++) {
                item = downstream[_k];
                if (item !== this) {
                  if ((_ref1 = item.trigger).call.apply(_ref1, [that, action].concat(__slice.call(args))) === true) {
                    return true;
                  }
                }
              }
              for (_l = 0, _len3 = upstream.length; _l < _len3; _l++) {
                item = upstream[_l];
                if (item !== this) {
                  if ((_ref2 = item.trigger).call.apply(_ref2, [that, action].concat(__slice.call(args))) === true) {
                    return true;
                  }
                }
              }
            }
          }
          return resolved;
        };
        return this.off = function(action, callback) {
          var actions, cbs, i, item, _i, _j, _len, _len1;

          if (!action) {
            callbacks = {};
            return;
          }
          actions = action.split(" ");
          for (_i = 0, _len = actions.length; _i < _len; _i++) {
            action = actions[_i];
            if (!callback) {
              delete callbacks[action];
            } else {
              cbs = callbacks[action];
              if (cbs) {
                for (i = _j = 0, _len1 = cbs.length; _j < _len1; i = ++_j) {
                  item = cbs[i];
                  if (item === callback) {
                    cbs.splice(i, 1);
                  }
                }
              }
            }
          }
          return this;
        };
      };
    };
    Attributed = function(attributes) {
      if (attributes == null) {
        attributes = {};
      }
      return function() {
        this.get = function(key) {
          return attributes[key];
        };
        this.all = function() {
          return attributes;
        };
        return this.set = function(key, value) {
          attributes[key] = value;
          this.trigger("change:" + key, value);
          return this.trigger("change", key, value);
        };
      };
    };
    Element = function(tag, html) {
      var binds, element, outlets;

      element = document.createElement(tag || "div");
      element.innerHTML = html || "";
      binds = {};
      outlets = {};
      return function() {
        var ev, rebuild, _i, _len, _ref,
          _this = this;

        rebuild = function() {
          var bindElements, el, name, outletElements, _i, _j, _len, _len1, _ref, _results;

          bindElements = element.querySelectorAll("[data-bind]");
          for (_i = 0, _len = bindElements.length; _i < _len; _i++) {
            el = bindElements[_i];
            name = el.getAttribute("data-bind");
            if ((_ref = binds[name]) == null) {
              binds[name] = [];
            }
            binds[name].push(el);
          }
          outletElements = element.querySelectorAll("[data-outlet]");
          _results = [];
          for (_j = 0, _len1 = outletElements.length; _j < _len1; _j++) {
            el = outletElements[_j];
            name = el.getAttribute("data-outlet");
            _results.push(outlets[name] = el);
          }
          return _results;
        };
        _ref = ["click", "dblclick", "keypress", "keydown", "keyup", "change"];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          ev = _ref[_i];
          element.addEventListener(ev, function(e) {
            var action, el, name, type;

            el = e.target;
            type = e.type;
            switch (type) {
              case "change":
                name = el.getAttribute("data-bind");
                if (name && el.type !== "checkbox") {
                  _this.trigger("change", name, el.value, el);
                  _this.trigger("change:" + name, el.value, el);
                }
                break;
              case "keydown":
                action = el.getAttribute("data-enter");
                if (e.keyCode === 13 && action && _this[action]) {
                  _this[action](e);
                }
                action = el.getAttribute("data-keydown");
                if (_this[action]) {
                  _this[action](e);
                }
                break;
              case "click":
                if (el.type === "checkbox") {
                  name = el.getAttribute("data-bind");
                  if (name) {
                    _this.trigger("change", name, el.checked, el);
                    _this.trigger("change:" + name, el.checked, el);
                  }
                } else {
                  action = el.getAttribute("data-click");
                  if (_this[action]) {
                    _this[action](e);
                  }
                }
                break;
              default:
                action = el.getAttribute("data-" + type);
                if (_this[action]) {
                  _this[action](e);
                }
            }
            return e.stopPropagation();
          });
        }
        rebuild();
        this.set = function(name, val) {
          var el, els, _j, _len1, _results;

          els = binds[name];
          if (!(els && els.length)) {
            return;
          }
          _results = [];
          for (_j = 0, _len1 = els.length; _j < _len1; _j++) {
            el = els[_j];
            tag = el.tagName.toLowerCase();
            if (tag === "input" || tag === "textarea" || tag === "select") {
              if (el.type === "checkbox") {
                el.checked = val;
              }
              _results.push(el.value = val);
            } else {
              _results.push(el.innerHTML = val);
            }
          }
          return _results;
        };
        this.get = function(name) {
          var el, els;

          els = binds[name];
          if (!(els && (el = els[0]))) {
            return void 0;
          }
          tag = el.tagName.toLowerCase();
          if (tag === "input" || tag === "textarea" || tag === "select") {
            if (el.type === "checkbox") {
              return el.checked;
            }
            return el.value;
          } else {
            return el.innerHTML;
          }
        };
        this.html = function(data) {
          if (!data) {
            return element.innerHTML;
          }
          element.innerHTML = data || "";
          rebuild();
          return this.trigger("reset", this);
        };
        this.insertInto = function(view, outlet) {
          var el;

          if (typeof view === "string") {
            el = document.querySelector(view);
            return el.appendChild(element);
          } else {
            return view.insert(element, outlet);
          }
        };
        this.insert = function(view, outlet) {
          if (view.insertInto) {
            return this.insertInto(this, outlet);
          } else {
            return outlets[outlet].appendChild(view);
          }
        };
        this.remove = function() {
          if (element.parentNode) {
            return element.parentNode.removeChild(element);
          }
        };
        return this.clean = function(outlet) {
          var el, _results, _results1;

          if (!outlet) {
            _results = [];
            for (outlet in outlets) {
              el = outlets[outlet];
              _results.push(this.clean(outlet));
            }
            return _results;
          } else {
            el = outlets[outlet];
            _results1 = [];
            while (el.firstChild) {
              _results1.push(el.removeChild(el.firstChild));
            }
            return _results1;
          }
        };
      };
    };
    Hiding = function(prop, val, set, get) {
      var value;

      value = null;
      return function() {
        this[prop] = function(newval) {
          if (!newval) {
            if (get) {
              return get.call(this, value);
            } else {
              return value;
            }
          } else {
            value = set ? set.call(this, value, newval) : newval;
            return this;
          }
        };
        return this[prop](val);
      };
    };
    Computing = function() {
      return function() {
        return this.computed = function(name, func, deps) {
          var change, dep, str, _i, _len,
            _this = this;

          this[name] = func;
          str = "";
          change = function() {
            var value;

            value = _this[name]();
            _this.trigger("change change:computed", name, value);
            return _this.trigger("change:" + name + " change:computed." + name, value);
          };
          for (_i = 0, _len = deps.length; _i < _len; _i++) {
            dep = deps[_i];
            if ((typeof dep === "function" && dep.type === "Model") || (typeof dep === "object" && dep.on)) {
              dep.on("change", change);
              dep.on("change:model", change);
            } else {
              str += "change:" + dep + " ";
            }
          }
          this.on(str, change);
          return change();
        };
      };
    };
    Base = (function() {
      function Base() {}

      Base.is = function(type) {
        return type.call(this);
      };

      Base.prototype.is = function(type) {
        return type.call(this);
      };

      Base.prototype.mixin = function(obj, ignore) {
        var key, val, _results;

        _results = [];
        for (key in obj) {
          val = obj[key];
          if (__indexOf.call(ignore, key) < 0) {
            _results.push(this[key] = val);
          }
        }
        return _results;
      };

      return Base;

    })();
    Model = (function(_super) {
      __extends(Model, _super);

      Model.type = "Model";

      function Model(data) {
        var _this = this;

        if (data == null) {
          data = {};
        }
        this.is(Evented("model"));
        this.is(Computing());
        this.is(Attributed(this.constructor.add(data)));
        this.on("change:view", function(key, val) {
          _this.set(key, val);
          return true;
        });
        this.on("reset:view", function(view) {
          var key, val, _ref;

          _ref = _this.all();
          for (key in _ref) {
            val = _ref[key];
            view.set(key, val);
          }
          return true;
        });
        this.attach(this.constructor, true);
        this.constructor.trigger("add", this);
        this.constructor.trigger("change");
      }

      Model.init = function() {
        var models;

        this.is(Evented("Model"));
        models = [];
        this.add = function(data) {
          var key, model, val;

          model = models[models.length] = {
            id: models.length
          };
          for (key in data) {
            val = data[key];
            model[key] = val;
          }
          return model;
        };
        this.remove = function(model) {
          this.trigger("remove", model);
          models.splice(models.indexOf(model), 1);
          return this.trigger("change");
        };
        this.reset = function(data) {
          var item, _i, _len;

          models = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            item = data[_i];
            new this(item);
          }
          this.trigger("reset", models);
          return this.trigger("change");
        };
        this.all = function() {
          return models.slice(0);
        };
        return this;
      };

      return Model;

    })(Base);
    View = (function(_super) {
      __extends(View, _super);

      function View(options) {
        var _this = this;

        if (options == null) {
          options = {};
        }
        this.is(Evented("view"));
        this.is(Element(options.tag || this.tag, options.html || this.html));
        this.is(Computing());
        this.mixin(options, ["tag", "html"]);
        this.on("change:model change:computed", function(key, val) {
          _this.set(key, val);
          return true;
        });
      }

      return View;

    })(Base);
    ViewModel = (function(_super) {
      __extends(ViewModel, _super);

      function ViewModel(options) {
        var setter;

        if (options == null) {
          options = {};
        }
        this.is(Evented());
        this.is(Computing());
        setter = function(old, val) {
          old && old.detach(this);
          val.attach(this);
          return val;
        };
        this.is(Hiding("model", options.model, setter));
        this.is(Hiding("view", options.view, setter));
        options.view.trigger("reset", options.view);
        this.mixin(options, ["model", "view"]);
      }

      return ViewModel;

    })(Base);
    ViewCollection = (function(_super) {
      __extends(ViewCollection, _super);

      function ViewCollection(options) {
        var add, remove, reset, viewmodels,
          _this = this;

        if (options == null) {
          options = {};
        }
        this.mixin(options, ["model"]);
        viewmodels = {};
        add = function(model) {
          var view;

          view = new (_this.view || options.view);
          viewmodels[model.get("id")] = new ViewModel({
            model: model,
            view: view
          });
          if (_this.parent) {
            return view.insertInto(_this.parent, _this.outlet);
          }
        };
        remove = function(model) {
          var id, viewmodel;

          id = model.id;
          viewmodel = viewmodels[id];
          viewmodel.view().remove();
          return delete viewmodels[id];
        };
        reset = function(data) {
          var model, _i, _len, _results;

          viewmodels = [];
          _this.parent.clean(_this.outlet);
          if (data) {
            _results = [];
            for (_i = 0, _len = data.length; _i < _len; _i++) {
              model = data[_i];
              _results.push(add(model));
            }
            return _results;
          }
        };
        this.is(Hiding("model", options.model, function(old, model) {
          if (old) {
            old.off("add", add);
            old.off("remove", remove);
            old.off("reset", reset);
          }
          model.on("add", add);
          model.on("remove", remove);
          model.on("reset", reset);
          return model;
        }));
      }

      return ViewCollection;

    })(Base);
    return {
      Model: Model,
      View: View,
      ViewModel: ViewModel,
      ViewCollection: ViewCollection
    };
  });

}).call(this);
