// Generated by CoffeeScript 1.6.2
(function() {
  var TodoView, Todos, app, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Todos = (function(_super) {
    __extends(Todos, _super);

    function Todos() {
      _ref = Todos.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return Todos;

  })(emvy.Model);

  Todos.init();

  TodoView = (function(_super) {
    __extends(TodoView, _super);

    function TodoView() {
      _ref1 = TodoView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    TodoView.prototype.html = '<b data-bind="title"></b><span data-bind="content"></span>';

    return TodoView;

  })(emvy.View);

  app = new emvy.ViewCollection({
    model: Todos,
    view: TodoView,
    parent: "body"
  });

  window.app = app;

  window.Todos = Todos;

  window.TodoView = TodoView;

}).call(this);
